
# This file is automatically generated, you probably don't want to edit this

anovacontrasttestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovacontrasttestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varEq = TRUE, ...) {

            super$initialize(
                package="anovacontrast",
                name="anovacontrasttest",
                requiresData=FALSE,
                ...)

            private$..varEq <- jmvcore::OptionBool$new(
                "varEq",
                varEq,
                default=TRUE)

            self$.addOption(private$..varEq)
        }),
    active = list(
        varEq = function() private$..varEq$value),
    private = list(
        ..varEq = NA)
)

anovacontrasttestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovacontrasttestResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="anovacontrasttest")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="anovacontrasttest"))}))

anovacontrasttestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovacontrasttestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "anovacontrast",
                name = "anovacontrasttest",
                version = c(1,0,0),
                options = options,
                results = anovacontrasttestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' anovacontrasttest
#'
#' 
#' @param varEq .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
anovacontrasttest <- function(
    varEq = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("anovacontrasttest requires jmvcore to be installed (restart may be required)")


    options <- anovacontrasttestOptions$new(
        varEq = varEq)

    analysis <- anovacontrasttestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

